from __future__ import annotations

import ast
import tokenize
from collections.abc import Iterator
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SELF = Path(__file__).resolve()

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "cutting-edge",
    "state-of-the-art",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
)

EMOJI_RANGES = (
    (0x2600, 0x27BF),
    (0x2B00, 0x2BFF),
    (0xFE00, 0xFE0F),
    (0x1F000, 0x1FAFF),
)

DEFINITION_NODES = (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def _python_files() -> Iterator[Path]:
    for base in ("causaldt_ad", "field_checks"):
        for path in sorted((ROOT / base).rglob("*.py")):
            if path.resolve() != SELF:
                yield path


def _has_emoji(text: str) -> bool:
    return any(any(lo <= ord(ch) <= hi for lo, hi in EMOJI_RANGES) for ch in text)


def test_sources_have_no_comments() -> None:
    for path in _python_files():
        with tokenize.open(path) as handle:
            for token in tokenize.generate_tokens(handle.readline):
                assert token.type != tokenize.COMMENT, path


def test_sources_have_no_docstrings() -> None:
    for path in _python_files():
        tree = ast.parse(path.read_text())
        for node in ast.walk(tree):
            if isinstance(node, DEFINITION_NODES):
                assert ast.get_docstring(node) is None, path


def test_no_forbidden_phrases() -> None:
    targets = list(_python_files()) + [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        lowered = path.read_text().lower()
        for phrase in FORBIDDEN:
            assert phrase not in lowered, (path, phrase)


def test_no_emoji() -> None:
    targets = list(_python_files()) + [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        assert not _has_emoji(path.read_text()), path
